name: prostore

options:
  bundleIdPrefix: com.prostoreios

configs:
  Release: release

packages:
  ProStoreTools:
    url: https://github.com/ProStore-iOS/ProStoreTools.git
    branch: main
  ZIPFoundation:
    url: https://github.com/weichsel/ZIPFoundation.git
    branch: main

targets:
  prostore:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources: [Sources/prostore]
    bundleId: com.prostoreios.prostore
    settings:
      IPHONEOS_DEPLOYMENT_TARGET: "16.0"
      ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
      SWIFT_OPTIMIZATION_LEVEL: "-Owholemodule"
    info:
      path: "Info.plist"
      properties:
        CFBundleDisplayName: "ProStore"
        CFBundleName: "prostore"
        CFBundleVersion: "1"
        CFBundleShortVersionString: "0.0.1"
        UILaunchStoryboardName: "LaunchScreen"
        NSPrincipalClass: "UIApplication"
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
        UIFileSharingEnabled: true
        LSSupportsOpeningDocumentsInPlace: true
        CFBundleURLTypes:
          - CFBundleURLName: "com.prostoreios.prostore"
            CFBundleURLSchemes:
              - prostore
              - ProStore
    dependencies:
      - package: ProStoreTools
        product: ProStoreTools
      - package: ZIPFoundation
        product: ZIPFoundation
