name: prostore

options:
  bundleIdPrefix: com.prostoreios

configs:
  Release: release

packages:
  Zsign-Package:
    url: https://github.com/khcrysalis/Zsign-Package.git
    branch: package
  ZIPFoundation:
    url: https://github.com/ProStore-iOS/IDeviceKit.git
    branch: main
  IDeviceKit:
    url: https://github.com/weichsel/ZIPFoundation.git
    branch: main
  OpenSSL:
    url: https://github.com/krzyzanowskim/OpenSSL.git
    from: "3.3.3001"

targets:
  prostore:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources: [Sources/prostore]
    bundleId: com.prostoreios.prostore
    settings:
      IPHONEOS_DEPLOYMENT_TARGET: "16.0"
      ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
      SWIFT_OPTIMIZATION_LEVEL: "-Owholemodule"
    info:
      path: "Info.plist"
      properties:
        CFBundleDisplayName: "ProStore"
        CFBundleName: "prostore"
        CFBundleVersion: "64"
        CFBundleShortVersionString: "1.2.2"
        UILaunchStoryboardName: "LaunchScreen"
        NSPrincipalClass: "UIApplication"
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
        UIFileSharingEnabled: true
        LSSupportsOpeningDocumentsInPlace: true
        CFBundleURLTypes:
          - CFBundleURLName: "com.prostoreios.prostore"
            CFBundleURLSchemes:
              - prostore
              - ProStore
    dependencies:
      - package: Zsign-Package
        product: ZsignSwift
      - package: ZIPFoundation
        product: ZIPFoundation
      - package: OpenSSL
        product: OpenSSL
      - package: IDeviceKit
        product: IDeviceSwift
